#!/bin/sh
set -eu

bundle=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
expected=@EXPECTED@
series=@SERIES@
version=@VERSION@
download_url=@URL@
download_hash=@SHA256@
runtime_name=@RUNTIME@
cache_suffix=@CACHE_SUFFIX@
target_system=@SYSTEM@
script_name=@SCRIPT@
launcher=@LAUNCHER@

fail() {
    printf 'portablepy: %s\n' "$*" >&2
    exit 1
}

file_hash() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        fail 'Python setup needs sha256sum or shasum to verify downloads.'
    fi
}

test_python() {
    [ -x "$1" ] || return 1
    "$1" -I -c '
import sys, json
from pathlib import Path
root = Path(sys.argv[3])
marker = root / ".portablepy-python"
candidate = str(Path(sys.argv[2]).absolute())
manifest_hash = sys.argv[4]
if sys.argv[5] == "cached":
    try:
        selected, encoded = marker.read_text(encoding="utf-8").splitlines()
        saved = json.loads(encoded)
        valid = selected == candidate and saved["manifest"] == manifest_hash and candidate in saved["files"]
        for name, expected in saved["files"].items():
            if expected is None:
                valid = valid and not Path(name).exists()
                continue
            status = Path(name).stat()
            valid = valid and [status.st_size, status.st_mtime_ns // 100] == expected
        sys.exit(0 if valid else 1)
    except (OSError, ValueError, KeyError, TypeError, AttributeError):
        sys.exit(1)

import struct, platform, sysconfig, venv, ensurepip
from importlib.util import MAGIC_NUMBER
actual = dict(implementation=sys.implementation.name, version=list(sys.version_info[:2]), full_version=list(sys.version_info[:3]), platform=sys.platform, machine=platform.machine().lower(), bits=struct.calcsize("P")*8, free_threaded=bool(sysconfig.get_config_var("Py_GIL_DISABLED")), cache_tag=sys.implementation.cache_tag, magic=MAGIC_NUMBER.hex(), release_level=sys.version_info.releaselevel, libc="musl" if "musl" in (sysconfig.get_config_var("HOST_GNU_TYPE") or "") or list(Path("/lib").glob("ld-musl-*.so.1")) else "gnu")
expected = json.loads(sys.argv[1])
if actual["release_level"] != "final" or any(actual.get(key) != value for key, value in expected.items()):
    sys.exit(1)
if sys.argv[5] == "check":
    sys.exit(0)

paths = {Path(candidate), Path(sys._base_executable)}
library = Path(sysconfig.get_config_var("LIBDIR") or "") / (sysconfig.get_config_var("LDLIBRARY") or "")
if library.is_file():
    paths.add(library)
paths.update((Path(candidate).parent / "pyvenv.cfg", Path(candidate).parent.parent / "pyvenv.cfg"))
saved = {"manifest": manifest_hash, "files": {}}
for path in paths:
    if not path.exists():
        saved["files"][str(path)] = None
        continue
    status = path.stat()
    saved["files"][str(path)] = [status.st_size, status.st_mtime_ns // 100]
if marker.is_symlink() or marker.resolve() != root / ".portablepy-python":
    sys.exit(1)
marker.write_text(candidate + "\n" + json.dumps(saved) + "\n", encoding="utf-8")
' "$expected" "$1" "$bundle" "$manifest_hash" "${2:-save}" >/dev/null 2>&1
}

write_launcher() {
    script="$bundle/$script_name"
    [ ! -L "$script" ] || fail "Launch script must not be a symlink: $script_name"
    if [ -e "$script" ] && [ "$(sed -n '2p' "$script")" != '# Generated by portablepy.' ]; then
        printf 'Leaving the existing %s unchanged; it was not created by portablepy.\n' "$script_name" >&2
        return
    fi
    temporary=$(mktemp "$bundle/.portablepy-launcher-XXXXXXXX")
    cat > "$temporary" <<'SCRIPT'
#!/bin/sh
# Generated by portablepy.
bundle=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P) || exit 1
python=$(sh "$bundle/python-setup.sh") || exit $?
SCRIPT
    printf 'exec "$python" -I "$bundle/%s" "$@"\n' "$launcher" >> "$temporary"
    chmod 755 "$temporary"
    mv -f "$temporary" "$script"
}

select_python() {
    write_launcher
    printf '%s\n' "$1"
    exit 0
}

[ "$(uname -s)" = "$target_system" ] || fail "This bundle requires $target_system."
manifest_hash=$(cat "$bundle/bundle.json.sha256")
[ "$(file_hash "$bundle/bundle.json")" = "$manifest_hash" ] || fail 'Bundle manifest checksum failed'

if [ "${PORTABLEPY_REFRESH_PYTHON:-}" != 1 ] && [ -f "$bundle/.portablepy-python" ]; then
    IFS= read -r selected < "$bundle/.portablepy-python" || selected=''
    if test_python "$selected" cached; then
        select_python "$selected"
    fi
fi

search_path=${PATH:-/usr/bin:/bin}
for name in "python$series" python3 python; do
    remaining=$search_path
    while :; do
        directory=${remaining%%:*}
        directory=${directory:-.}
        candidate="$directory/$name"
        if test_python "$candidate"; then
            directory=$(CDPATH= cd -- "$directory" && pwd -P)
            select_python "$directory/$name"
        fi
        case "$remaining" in
            *:*) remaining=${remaining#*:} ;;
            *) break ;;
        esac
    done
done

if [ "$target_system" = Darwin ]; then
    runtime_base="$HOME/Library/Application Support/portablepy"
else
    runtime_base="${XDG_DATA_HOME:-$HOME/.local/share}/portablepy"
fi
case "$runtime_base" in
    /*) ;;
    *) fail 'The Python cache needs an absolute user application data path.' ;;
esac
runtime_root="$runtime_base/$runtime_name"
runtime_python="$runtime_root/bin/python$series"
[ ! -L "$runtime_base" ] && [ ! -L "$runtime_root" ] || fail 'Local runtime folders must not be symlinks'
for cached in "$runtime_base"/python-"$series".*-"$cache_suffix"; do
    [ ! -L "$cached" ] && [ -d "$cached" ] || continue
    [ -f "$cached/.portablepy-runtime.sha256" ] || continue
    cached_hash=$(cat "$cached/.portablepy-runtime.sha256")
    case "$cached_hash" in
        ''|*[!0123456789abcdef]*) continue ;;
    esac
    [ "${#cached_hash}" -eq 64 ] || continue
    if test_python "$cached/bin/python$series"; then
        select_python "$cached/bin/python$series"
    fi
done
[ ! -e "$runtime_root" ] || fail "The local runtime folder is incomplete or unrelated: $runtime_root. Rename it and retry."

mkdir -p "$runtime_base"
[ ! -L "$runtime_base" ] || fail 'The runtime cache must not be a symlink'
lock="$runtime_root.lock"
mkdir "$lock" 2>/dev/null || fail "Another Python download is running. If it was interrupted, remove $lock and retry."
work=''
cleanup() {
    case "$work" in
        "$runtime_base"/.portablepy-runtime-*) rm -rf -- "$work" ;;
    esac
    rmdir "$lock"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
work=$(mktemp -d "$runtime_base/.portablepy-runtime-XXXXXXXX")
archive="$work/python.tar.gz"
printf 'Downloading Python %s from Astral python-build-standalone...\n' "$version" >&2
case "$download_url" in
    https://github.com/astral-sh/python-build-standalone/releases/download/*-install_only_stripped.tar.gz) ;;
    *) fail 'Invalid Astral Python download URL' ;;
esac
if command -v curl >/dev/null 2>&1; then
    curl --fail --location --silent --show-error --proto '=https' --proto-redir '=https' --connect-timeout 30 --max-time 300 --output "$archive" "$download_url"
else
    fail 'Python setup needs curl to download a local runtime.'
fi
[ "$(file_hash "$archive")" = "$download_hash" ] || fail 'Downloaded Python runtime failed its SHA-256 check'
tar -tzf "$archive" > "$work/members"
while IFS= read -r member; do
    member=${member%/}
    case "$member" in
        python|python/*) ;;
        *) fail "Unsafe path in Python runtime: $member" ;;
    esac
    case "/$member/" in
        */../*|*/./*|*//*) fail "Unsafe path in Python runtime: $member" ;;
    esac
done < "$work/members"
staged="$work/runtime"
mkdir "$staged"
tar -xzf "$archive" --strip-components=1 --no-same-owner -C "$staged"
test_python "$staged/bin/python$series" check || fail 'Downloaded Python does not match this bundle runtime'
rm -rf -- "$staged/include" "$staged/share/man"
rm -f -- "$staged/lib/libpython$series.a"
printf '%s\n' "$download_hash" > "$staged/.portablepy-runtime.sha256"
mkdir -p "$runtime_base"
[ ! -L "$runtime_base" ] && [ ! -e "$runtime_root" ] && [ ! -L "$runtime_root" ] || fail 'Runtime destination changed during setup'
mv "$staged" "$runtime_root"
test_python "$runtime_python" || fail 'Installed Python does not match this bundle runtime'
select_python "$runtime_python"
