$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$BundleRoot = [IO.Path]::GetFullPath($PSScriptRoot)
Import-Module (Join-Path $PSHOME 'Modules/Microsoft.PowerShell.Utility')

function Test-Python([string] $Candidate) {
    if (-not (Test-Path -LiteralPath $Candidate -PathType Leaf)) {
        return $false
    }
    $Probe = @'
import sys, struct, platform, json, sysconfig, venv, ensurepip
from importlib.util import MAGIC_NUMBER
print(json.dumps(dict(implementation=sys.implementation.name, version=list(sys.version_info[:2]), full_version=list(sys.version_info[:3]), platform=sys.platform, machine=platform.machine().lower(), bits=struct.calcsize('P')*8, free_threaded=bool(sysconfig.get_config_var('Py_GIL_DISABLED')), cache_tag=sys.implementation.cache_tag, magic=MAGIC_NUMBER.hex(), release_level=sys.version_info.releaselevel)))
'@
    try {
        $Output = & $Candidate -I -c $Probe 2>$null
        if ($LASTEXITCODE -ne 0) {
            return $false
        }
        $Actual = $Output | ConvertFrom-Json
        if ($Actual.release_level -ne 'final') {
            return $false
        }
        foreach ($Property in $Manifest.runtime.PSObject.Properties) {
            $ActualValue = $Actual.($Property.Name)
            if (($ActualValue | ConvertTo-Json -Compress) -cne ($Property.Value | ConvertTo-Json -Compress)) {
                return $false
            }
        }
        return $true
    }
    catch {
        return $false
    }
}

function Assert-LocalPath([string] $Path) {
    $FullPath = [IO.Path]::GetFullPath($Path)
    if (-not $FullPath.StartsWith($BundleRoot + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Runtime path is outside the bundle: $Path"
    }
    if ((Test-Path -LiteralPath $FullPath) -and ((Get-Item -LiteralPath $FullPath -Force).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw "Runtime path must not be a symlink or junction: $Path"
    }
}

function Assert-CachePath([string] $Path) {
    $FullPath = [IO.Path]::GetFullPath($Path)
    if ($FullPath -ne $RuntimeBase -and -not $FullPath.StartsWith($RuntimeBase + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Runtime path is outside the portablepy cache: $Path"
    }
    if ((Test-Path -LiteralPath $FullPath) -and ((Get-Item -LiteralPath $FullPath -Force).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw "Runtime path must not be a symlink or junction: $Path"
    }
}

function Write-LaunchScript {
    $Launcher = if ($Manifest.compile -eq 'all') { 'run.pyc' } else { 'run.py' }
    $Script = @'
@rem Generated by portablepy.
@echo off
setlocal DisableDelayedExpansion
set "portablepy_python="
for /f "usebackq delims=" %%P in (`powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "%~dp0python-setup.ps1"`) do set "portablepy_python=%%P"
if not defined portablepy_python exit /b 1
"%portablepy_python%" -I "%~dp0{launcher}" %*
exit /b %errorlevel%
'@
    $Script = ($Script.Replace('{launcher}', $Launcher) -replace '\r?\n', "`r`n") + "`r`n"
    $ScriptPath = Join-Path $BundleRoot 'run.cmd'
    Assert-LocalPath $ScriptPath
    if (Test-Path -LiteralPath $ScriptPath) {
        $Existing = [IO.File]::ReadAllText($ScriptPath)
        if (-not $Existing.StartsWith('@rem Generated by portablepy.')) {
            [Console]::Error.WriteLine('Leaving the existing run.cmd unchanged; it was not created by portablepy.')
            return
        }
        if ($Existing -ceq $Script) {
            return
        }
    }
    [IO.File]::WriteAllText($ScriptPath, $Script, [Text.Encoding]::ASCII)
}

try {
    $ManifestPath = Join-Path $BundleRoot 'bundle.json'
    $ExpectedHash = (Get-Content -LiteralPath ($ManifestPath + '.sha256') -Raw).Trim()
    if ((Get-FileHash -LiteralPath $ManifestPath -Algorithm SHA256).Hash -ine $ExpectedHash) {
        throw 'Bundle manifest checksum failed'
    }
    $Manifest = Get-Content -LiteralPath $ManifestPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $Download = $Manifest.python_download
    $DownloadUri = [Uri]$Download.url
    if ($DownloadUri.Scheme -ne 'https' -or $DownloadUri.Authority -ne 'www.python.org' -or -not $DownloadUri.AbsolutePath.StartsWith('/ftp/python/') -or $DownloadUri.Query -or $DownloadUri.Fragment -or $Download.sha256 -cnotmatch '^[0-9a-f]{64}$') {
        throw 'Invalid official Python download information'
    }

    $Candidates = [Collections.Generic.List[string]]::new()
    $PythonLauncher = Get-Command py.exe -ErrorAction SilentlyContinue
    if ($PythonLauncher) {
        try {
            $Installed = & $PythonLauncher.Source -0p 2>$null
            foreach ($Line in $Installed) {
                if ($Line -match '^\s*-\S+\s+\*?\s*(.+?\.exe)\s*$') {
                    $Candidates.Add($Matches[1])
                }
            }
        }
        catch {
            # PATH candidates are still available when the launcher cannot list Python.
        }
    }
    $Series = $Manifest.runtime.version -join '.'
    foreach ($Name in @("python$Series.exe", 'python3.exe', 'python.exe')) {
        foreach ($Command in @(Get-Command $Name -CommandType Application -All -ErrorAction SilentlyContinue)) {
            if ($Command.Source -notlike '*\Microsoft\WindowsApps\*') {
                $Candidates.Add($Command.Source)
            }
        }
    }
    foreach ($Candidate in ($Candidates | Select-Object -Unique)) {
        if (Test-Python $Candidate) {
            Write-LaunchScript
            Write-Output $Candidate
            exit 0
        }
    }

    $UserData = $env:LOCALAPPDATA
    if (-not $UserData) {
        $UserData = [Environment]::GetFolderPath('LocalApplicationData')
    }
    if (-not $UserData -or -not [IO.Path]::IsPathRooted($UserData)) {
        throw 'Cannot find the local application data directory for the Python cache'
    }
    $RuntimeBase = [IO.Path]::GetFullPath((Join-Path $UserData 'portablepy'))
    Assert-CachePath $RuntimeBase
    if ($Download.version -cnotmatch '^3\.[0-9]+\.[0-9]+$' -or $Download.architecture -notin @('32', '64', 'arm64')) {
        throw 'Invalid Python runtime version or architecture'
    }
    $RuntimeName = 'python-' + $Download.version + '-' + $Download.architecture
    $RuntimeRoot = Join-Path $RuntimeBase $RuntimeName
    Assert-CachePath $RuntimeRoot
    $RuntimePython = Join-Path $RuntimeRoot 'python.exe'
    if (Test-Path -LiteralPath $RuntimeBase) {
        foreach ($Cached in (Get-ChildItem -LiteralPath $RuntimeBase -Directory -Filter 'python-*' | Sort-Object Name -Descending)) {
            if ($Cached.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                continue
            }
            $MarkerPath = Join-Path $Cached.FullName '.portablepy-runtime.json'
            if (-not (Test-Path -LiteralPath $MarkerPath -PathType Leaf)) {
                continue
            }
            try {
                $Marker = Get-Content -LiteralPath $MarkerPath -Raw -Encoding UTF8 | ConvertFrom-Json
                $ValidMarker = $Marker.sha256 -cmatch '^[0-9a-f]{64}$' -and $Marker.architecture -eq $Download.architecture -and $Cached.Name -eq ('python-' + $Marker.version + '-' + $Marker.architecture)
            }
            catch {
                continue
            }
            $CachedPython = Join-Path $Cached.FullName 'python.exe'
            if ($ValidMarker -and (Test-Python $CachedPython)) {
                Write-LaunchScript
                Write-Output $CachedPython
                exit 0
            }
        }
    }
    if (Test-Path -LiteralPath $RuntimeRoot) {
        throw "The local runtime folder is incomplete or unrelated: $RuntimeRoot. Rename it and retry."
    }

    [void][IO.Directory]::CreateDirectory($RuntimeBase)
    Assert-CachePath $RuntimeBase
    $LockPath = Join-Path $RuntimeBase ($RuntimeName + '.lock')
    Assert-CachePath $LockPath
    try {
        $Lock = [IO.File]::Open($LockPath, [IO.FileMode]::CreateNew, [IO.FileAccess]::Write, [IO.FileShare]::None)
    }
    catch {
        throw "Another Python download is running. If it was interrupted, remove $LockPath and retry."
    }
    $Work = Join-Path $RuntimeBase ('.portablepy-runtime-' + [Guid]::NewGuid().ToString('N'))
    Assert-CachePath $Work
    try {
        [void][IO.Directory]::CreateDirectory($Work)
        $Archive = Join-Path $Work 'python.zip'
        [Console]::Error.WriteLine("Downloading Python $($Download.version) from python.org...")
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $Download.url -OutFile $Archive -UseBasicParsing -TimeoutSec 60 -MaximumRedirection 0
        if ((Get-FileHash -LiteralPath $Archive -Algorithm SHA256).Hash -ine $Download.sha256) {
            throw 'Downloaded Python runtime failed its SHA-256 check'
        }
        $Staged = Join-Path $Work 'runtime'
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        $Zip = [IO.Compression.ZipFile]::OpenRead($Archive)
        try {
            foreach ($Entry in $Zip.Entries) {
                $Relative = $Entry.FullName.Replace('\', '/')
                $Parts = $Relative.TrimEnd('/').Split('/')
                if (@($Parts | Where-Object { $_ -in @('', '.', '..') -or $_.Contains(':') }).Count) {
                    throw "Unsafe path in Python runtime: $Relative"
                }
                if ($Parts[0] -in @('Doc', 'include', 'libs')) {
                    continue
                }
                $Target = Join-Path $Staged $Relative
                Assert-CachePath $Target
                if ($Relative.EndsWith('/')) {
                    [void][IO.Directory]::CreateDirectory($Target)
                }
                else {
                    [void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Target))
                    [IO.Compression.ZipFileExtensions]::ExtractToFile($Entry, $Target)
                }
            }
        }
        finally {
            $Zip.Dispose()
        }
        if (-not (Test-Python (Join-Path $Staged 'python.exe'))) {
            throw 'Downloaded Python does not match this bundle runtime'
        }
        $Download | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $Staged '.portablepy-runtime.json') -Encoding UTF8
        [void][IO.Directory]::CreateDirectory($RuntimeBase)
        Assert-CachePath $RuntimeBase
        Assert-CachePath $RuntimeRoot
        Move-Item -LiteralPath $Staged -Destination $RuntimeRoot
    }
    finally {
        if (Test-Path -LiteralPath $Work) {
            Assert-CachePath $Work
            Remove-Item -LiteralPath $Work -Recurse -Force
        }
        $Lock.Dispose()
        Remove-Item -LiteralPath $LockPath -Force
    }
    Write-LaunchScript
    Write-Output $RuntimePython
}
catch {
    [Console]::Error.WriteLine("portablepy: $($_.Exception.Message)")
    exit 1
}
